import { RobloxRole, RobloxMember, WallPost, Payout } from "@/types/admin";

export const mockRoles: RobloxRole[] = [
  {
    id: 1,
    name: "Owner",
    rank: 255,
    memberCount: 1,
    permissions: ["all"],
    color: "#FFD700",
  },
  {
    id: 2,
    name: "Administrator",
    rank: 200,
    memberCount: 5,
    permissions: ["manage_members", "manage_wall", "manage_payouts", "manage_roles"],
    color: "#FF6B6B",
  },
  {
    id: 3,
    name: "Moderator",
    rank: 150,
    memberCount: 12,
    permissions: ["manage_wall", "view_members", "kick_members"],
    color: "#4ECDC4",
  },
  {
    id: 4,
    name: "Developer",
    rank: 100,
    memberCount: 8,
    permissions: ["view_payouts", "post_wall", "view_analytics"],
    color: "#9B59B6",
  },
  {
    id: 5,
    name: "Contributor",
    rank: 50,
    memberCount: 45,
    permissions: ["post_wall", "view_wall"],
    color: "#3498DB",
  },
  {
    id: 6,
    name: "Member",
    rank: 1,
    memberCount: 1250,
    permissions: ["view_wall"],
    color: "#95A5A6",
  },
];

export const mockMembers: RobloxMember[] = [
  {
    id: 1,
    username: "WhimcoOwner",
    displayName: "Whimco Official",
    avatarUrl: "https://tr.rbxcdn.com/30DAY-AvatarHeadshot-placeholder/150/150/AvatarHeadshot/Webp/noFilter",
    role: mockRoles[0],
    joinDate: "2023-01-15",
    lastActive: "2024-01-13",
    totalEarnings: 125000,
  },
  {
    id: 2,
    username: "DevMaster99",
    displayName: "Dev Master",
    avatarUrl: "https://tr.rbxcdn.com/30DAY-AvatarHeadshot-placeholder/150/150/AvatarHeadshot/Webp/noFilter",
    role: mockRoles[1],
    joinDate: "2023-02-20",
    lastActive: "2024-01-12",
    totalEarnings: 45000,
  },
  {
    id: 3,
    username: "ModHelper",
    displayName: "Helpful Mod",
    avatarUrl: "https://tr.rbxcdn.com/30DAY-AvatarHeadshot-placeholder/150/150/AvatarHeadshot/Webp/noFilter",
    role: mockRoles[2],
    joinDate: "2023-03-10",
    lastActive: "2024-01-13",
    totalEarnings: 12000,
  },
  {
    id: 4,
    username: "ScriptWizard",
    displayName: "Script Wizard",
    avatarUrl: "https://tr.rbxcdn.com/30DAY-AvatarHeadshot-placeholder/150/150/AvatarHeadshot/Webp/noFilter",
    role: mockRoles[3],
    joinDate: "2023-04-05",
    lastActive: "2024-01-11",
    totalEarnings: 28000,
  },
  {
    id: 5,
    username: "BuilderPro",
    displayName: "Pro Builder",
    avatarUrl: "https://tr.rbxcdn.com/30DAY-AvatarHeadshot-placeholder/150/150/AvatarHeadshot/Webp/noFilter",
    role: mockRoles[3],
    joinDate: "2023-04-15",
    lastActive: "2024-01-10",
    totalEarnings: 22000,
  },
  {
    id: 6,
    username: "ArtistCreative",
    displayName: "Creative Artist",
    avatarUrl: "https://tr.rbxcdn.com/30DAY-AvatarHeadshot-placeholder/150/150/AvatarHeadshot/Webp/noFilter",
    role: mockRoles[4],
    joinDate: "2023-05-20",
    lastActive: "2024-01-09",
    totalEarnings: 8500,
  },
  {
    id: 7,
    username: "GameTester1",
    displayName: "Game Tester",
    avatarUrl: "https://tr.rbxcdn.com/30DAY-AvatarHeadshot-placeholder/150/150/AvatarHeadshot/Webp/noFilter",
    role: mockRoles[5],
    joinDate: "2023-08-10",
    lastActive: "2024-01-08",
    totalEarnings: 0,
  },
  {
    id: 8,
    username: "NewPlayer2024",
    displayName: "New Player",
    avatarUrl: "https://tr.rbxcdn.com/30DAY-AvatarHeadshot-placeholder/150/150/AvatarHeadshot/Webp/noFilter",
    role: mockRoles[5],
    joinDate: "2024-01-05",
    lastActive: "2024-01-13",
    totalEarnings: 0,
  },
];

export const mockWallPosts: WallPost[] = [
  {
    id: 1,
    author: {
      id: 1,
      username: "WhimcoOwner",
      displayName: "Whimco Official",
      avatarUrl: "https://tr.rbxcdn.com/30DAY-AvatarHeadshot-placeholder/150/150/AvatarHeadshot/Webp/noFilter",
    },
    content: "Welcome to Whimco! Check out our latest game update - tons of new features and bug fixes. Thank you all for your support!",
    createdAt: "2024-01-12T14:30:00Z",
    isPinned: true,
    isHidden: false,
  },
  {
    id: 2,
    author: {
      id: 2,
      username: "DevMaster99",
      displayName: "Dev Master",
      avatarUrl: "https://tr.rbxcdn.com/30DAY-AvatarHeadshot-placeholder/150/150/AvatarHeadshot/Webp/noFilter",
    },
    content: "New developer tools are now available! Check the documentation for the latest API changes.",
    createdAt: "2024-01-11T10:15:00Z",
    isPinned: false,
    isHidden: false,
  },
  {
    id: 3,
    author: {
      id: 3,
      username: "ModHelper",
      displayName: "Helpful Mod",
      avatarUrl: "https://tr.rbxcdn.com/30DAY-AvatarHeadshot-placeholder/150/150/AvatarHeadshot/Webp/noFilter",
    },
    content: "Reminder: Please follow the community guidelines. Any violations will result in warnings or removal.",
    createdAt: "2024-01-10T16:45:00Z",
    isPinned: false,
    isHidden: false,
  },
  {
    id: 4,
    author: {
      id: 6,
      username: "ArtistCreative",
      displayName: "Creative Artist",
      avatarUrl: "https://tr.rbxcdn.com/30DAY-AvatarHeadshot-placeholder/150/150/AvatarHeadshot/Webp/noFilter",
    },
    content: "Just finished the new character designs! Can't wait for everyone to see them in the next update.",
    createdAt: "2024-01-09T09:20:00Z",
    isPinned: false,
    isHidden: false,
  },
  {
    id: 5,
    author: {
      id: 7,
      username: "GameTester1",
      displayName: "Game Tester",
      avatarUrl: "https://tr.rbxcdn.com/30DAY-AvatarHeadshot-placeholder/150/150/AvatarHeadshot/Webp/noFilter",
    },
    content: "Found a bug in level 5 - the door doesn't open after collecting all keys. Reported to devs!",
    createdAt: "2024-01-08T13:00:00Z",
    isPinned: false,
    isHidden: false,
  },
  {
    id: 6,
    author: {
      id: 8,
      username: "SpammerUser",
      displayName: "Bad Actor",
      avatarUrl: "https://tr.rbxcdn.com/30DAY-AvatarHeadshot-placeholder/150/150/AvatarHeadshot/Webp/noFilter",
    },
    content: "[Hidden content - spam/inappropriate]",
    createdAt: "2024-01-07T22:30:00Z",
    isPinned: false,
    isHidden: true,
  },
];

export const mockPayouts: Payout[] = [
  {
    id: 1,
    recipient: {
      id: 2,
      username: "DevMaster99",
      displayName: "Dev Master",
      avatarUrl: "https://tr.rbxcdn.com/30DAY-AvatarHeadshot-placeholder/150/150/AvatarHeadshot/Webp/noFilter",
    },
    amount: 5000,
    percentage: 25,
    date: "2024-01-10",
    status: "completed",
    note: "Monthly developer bonus - January 2024",
  },
  {
    id: 2,
    recipient: {
      id: 4,
      username: "ScriptWizard",
      displayName: "Script Wizard",
      avatarUrl: "https://tr.rbxcdn.com/30DAY-AvatarHeadshot-placeholder/150/150/AvatarHeadshot/Webp/noFilter",
    },
    amount: 3500,
    percentage: 17.5,
    date: "2024-01-10",
    status: "completed",
    note: "Script optimization work",
  },
  {
    id: 3,
    recipient: {
      id: 5,
      username: "BuilderPro",
      displayName: "Pro Builder",
      avatarUrl: "https://tr.rbxcdn.com/30DAY-AvatarHeadshot-placeholder/150/150/AvatarHeadshot/Webp/noFilter",
    },
    amount: 2800,
    percentage: 14,
    date: "2024-01-10",
    status: "completed",
    note: "New map building",
  },
  {
    id: 4,
    recipient: {
      id: 3,
      username: "ModHelper",
      displayName: "Helpful Mod",
      avatarUrl: "https://tr.rbxcdn.com/30DAY-AvatarHeadshot-placeholder/150/150/AvatarHeadshot/Webp/noFilter",
    },
    amount: 1500,
    percentage: 7.5,
    date: "2024-01-10",
    status: "completed",
    note: "Moderation bonus",
  },
  {
    id: 5,
    recipient: {
      id: 6,
      username: "ArtistCreative",
      displayName: "Creative Artist",
      avatarUrl: "https://tr.rbxcdn.com/30DAY-AvatarHeadshot-placeholder/150/150/AvatarHeadshot/Webp/noFilter",
    },
    amount: 2000,
    percentage: 10,
    date: "2024-01-12",
    status: "pending",
    note: "Character design work",
  },
  {
    id: 6,
    recipient: {
      id: 4,
      username: "ScriptWizard",
      displayName: "Script Wizard",
      avatarUrl: "https://tr.rbxcdn.com/30DAY-AvatarHeadshot-placeholder/150/150/AvatarHeadshot/Webp/noFilter",
    },
    amount: 1200,
    percentage: 6,
    date: "2024-01-13",
    status: "pending",
    note: "Bug fix sprint bonus",
  },
];

// Summary stats
export const mockRobloxSummary = {
  totalMembers: mockMembers.length + 1310, // Including non-listed members
  activeMembers: 856,
  totalRoles: mockRoles.length,
  wallPosts: mockWallPosts.filter((p) => !p.isHidden).length,
  pendingPayouts: mockPayouts.filter((p) => p.status === "pending").length,
  totalPaidThisMonth: mockPayouts
    .filter((p) => p.status === "completed")
    .reduce((sum, p) => sum + p.amount, 0),
};
